---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: "v4.3.0"
    hooks:
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-xml
      - id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.28.0"
    hooks:
      - id: yamllint
        name: "YAML Syntax Check"
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: "v6.8.6"
    hooks:
      - id: ansible-lint
